python get_video_embedding.py --cuda 'cuda:0' --path_x '/raid/yinghua/VRank/data/pkl_data/ucf101/ucf101_x.pkl' --save_video_embedding '/raid/yinghua/VRank/data/pkl_data/ucf101/ucf101_x_embedding.pkl'
python get_video_embedding.py --cuda 'cuda:0' --path_x '/raid/yinghua/VRank/data/pkl_data/ucf_noise/augmentation_channel_shift_range_x.pkl' --save_video_embedding '/raid/yinghua/VRank/data/pkl_data/ucf_noise/augmentation_channel_shift_range_x_embedding.pkl'
python get_video_embedding.py --cuda 'cuda:0' --path_x '/raid/yinghua/VRank/data/pkl_data/ucf_noise/augmentation_featurewise_std_normalization_x.pkl' --save_video_embedding '/raid/yinghua/VRank/data/pkl_data/ucf_noise/augmentation_featurewise_std_normalization_x_embedding.pkl'
python get_video_embedding.py --cuda 'cuda:0' --path_x '/raid/yinghua/VRank/data/pkl_data/ucf_noise/augmentation_height_shift_x.pkl' --save_video_embedding '/raid/yinghua/VRank/data/pkl_data/ucf_noise/augmentation_height_shift_x_embedding.pkl'
python get_video_embedding.py --cuda 'cuda:0' --path_x '/raid/yinghua/VRank/data/pkl_data/ucf_noise/augmentation_horizontal_flip_x.pkl' --save_video_embedding '/raid/yinghua/VRank/data/pkl_data/ucf_noise/augmentation_horizontal_flip_x_embedding.pkl'
python get_video_embedding.py --cuda 'cuda:0' --path_x '/raid/yinghua/VRank/data/pkl_data/ucf_noise/augmentation_shear_range_x.pkl' --save_video_embedding '/raid/yinghua/VRank/data/pkl_data/ucf_noise/augmentation_shear_range_x_embedding.pkl'
python get_video_embedding.py --cuda 'cuda:0' --path_x '/raid/yinghua/VRank/data/pkl_data/ucf_noise/augmentation_width_shift_x.pkl' --save_video_embedding '/raid/yinghua/VRank/data/pkl_data/ucf_noise/augmentation_width_shift_x_embedding.pkl'
python get_video_embedding.py --cuda 'cuda:0' --path_x '/raid/yinghua/VRank/data/pkl_data/ucf_noise/augmentation_zca_whitening_x.pkl' --save_video_embedding '/raid/yinghua/VRank/data/pkl_data/ucf_noise/augmentation_zca_whitening_x_embedding.pkl'

python get_video_embedding.py --cuda 'cuda:0' --path_x '/raid/yinghua/VRank/data/pkl_data/hmdb51/hmdb51_x.pkl' --save_video_embedding '/raid/yinghua/VRank/data/pkl_data/hmdb51/hmdb51_x_embedding.pkl'
python get_video_embedding.py --cuda 'cuda:0' --path_x '/raid/yinghua/VRank/data/pkl_data/hmdb_noise/augmentation_channel_shift_range_x.pkl' --save_video_embedding '/raid/yinghua/VRank/data/pkl_data/hmdb_noise/augmentation_channel_shift_range_x_embedding.pkl'
python get_video_embedding.py --cuda 'cuda:0' --path_x '/raid/yinghua/VRank/data/pkl_data/hmdb_noise/augmentation_featurewise_std_normalization_x.pkl' --save_video_embedding '/raid/yinghua/VRank/data/pkl_data/hmdb_noise/augmentation_featurewise_std_normalization_x_embedding.pkl'
python get_video_embedding.py --cuda 'cuda:0' --path_x '/raid/yinghua/VRank/data/pkl_data/hmdb_noise/augmentation_height_shift_x.pkl' --save_video_embedding '/raid/yinghua/VRank/data/pkl_data/hmdb_noise/augmentation_height_shift_x_embedding.pkl'
python get_video_embedding.py --cuda 'cuda:0' --path_x '/raid/yinghua/VRank/data/pkl_data/hmdb_noise/augmentation_horizontal_flip_x.pkl' --save_video_embedding '/raid/yinghua/VRank/data/pkl_data/hmdb_noise/augmentation_horizontal_flip_x_embedding.pkl'
python get_video_embedding.py --cuda 'cuda:0' --path_x '/raid/yinghua/VRank/data/pkl_data/hmdb_noise/augmentation_shear_range_x.pkl' --save_video_embedding '/raid/yinghua/VRank/data/pkl_data/hmdb_noise/augmentation_shear_range_x_embedding.pkl'
python get_video_embedding.py --cuda 'cuda:0' --path_x '/raid/yinghua/VRank/data/pkl_data/hmdb_noise/augmentation_width_shift_x.pkl' --save_video_embedding '/raid/yinghua/VRank/data/pkl_data/hmdb_noise/augmentation_width_shift_x_embedding.pkl'
python get_video_embedding.py --cuda 'cuda:0' --path_x '/raid/yinghua/VRank/data/pkl_data/hmdb_noise/augmentation_zca_whitening_x.pkl' --save_video_embedding '/raid/yinghua/VRank/data/pkl_data/hmdb_noise/augmentation_zca_whitening_x_embedding.pkl'

python get_video_embedding.py --cuda 'cuda:0' --path_x '/raid/yinghua/VRank/data/pkl_data/accident/accident_x.pkl' --save_video_embedding '/raid/yinghua/VRank/data/pkl_data/accident/accident_x_embedding.pkl'
python get_video_embedding.py --cuda 'cuda:0' --path_x '/raid/yinghua/VRank/data/pkl_data/accident_noise/augmentation_channel_shift_range_x.pkl' --save_video_embedding '/raid/yinghua/VRank/data/pkl_data/accident_noise/augmentation_channel_shift_range_x_embedding.pkl'
python get_video_embedding.py --cuda 'cuda:0' --path_x '/raid/yinghua/VRank/data/pkl_data/accident_noise/augmentation_featurewise_std_normalization_x.pkl' --save_video_embedding '/raid/yinghua/VRank/data/pkl_data/accident_noise/augmentation_featurewise_std_normalization_x_embedding.pkl'
python get_video_embedding.py --cuda 'cuda:0' --path_x '/raid/yinghua/VRank/data/pkl_data/accident_noise/augmentation_height_shift_x.pkl' --save_video_embedding '/raid/yinghua/VRank/data/pkl_data/accident_noise/augmentation_height_shift_x_embedding.pkl'
python get_video_embedding.py --cuda 'cuda:0' --path_x '/raid/yinghua/VRank/data/pkl_data/accident_noise/augmentation_horizontal_flip_x.pkl' --save_video_embedding '/raid/yinghua/VRank/data/pkl_data/accident_noise/augmentation_horizontal_flip_x_embedding.pkl'
python get_video_embedding.py --cuda 'cuda:0' --path_x '/raid/yinghua/VRank/data/pkl_data/accident_noise/augmentation_shear_range_x.pkl' --save_video_embedding '/raid/yinghua/VRank/data/pkl_data/accident_noise/augmentation_shear_range_x_embedding.pkl'
python get_video_embedding.py --cuda 'cuda:0' --path_x '/raid/yinghua/VRank/data/pkl_data/accident_noise/augmentation_width_shift_x.pkl' --save_video_embedding '/raid/yinghua/VRank/data/pkl_data/accident_noise/augmentation_width_shift_x_embedding.pkl'
python get_video_embedding.py --cuda 'cuda:0' --path_x '/raid/yinghua/VRank/data/pkl_data/accident_noise/augmentation_zca_whitening_x.pkl' --save_video_embedding '/raid/yinghua/VRank/data/pkl_data/accident_noise/augmentation_zca_whitening_x_embedding.pkl'



