python vrank_apfd_evaluation.py --save_path_name 'apfd_ucf101_C3D_18.csv' --save_col_name 'original' --path_x './pkl_data/ucf101/ucf101_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_val_pre './target_models/ucf101_C3D_18_val_pre.pkl' --path_test_pre './target_models/ucf101_C3D_18_test_pre.pkl' --path_x_embedding './pkl_data/ucf101/ucf101_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_ucf101_C3D_18.csv' --save_col_name 'channel_shift_range' --path_x './pkl_data/ucf_noise/augmentation_channel_shift_range_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_val_pre './pkl_data/ucf_noise/ucf101_C3D_18_val_augmentation_channel_shift_range_x_pre.pkl' --path_test_pre './pkl_data/ucf_noise/ucf101_C3D_18_test_augmentation_channel_shift_range_x_pre.pkl' --path_x_embedding './pkl_data/ucf_noise/augmentation_channel_shift_range_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_ucf101_C3D_18.csv' --save_col_name 'featurewise_std_normalization' --path_x './pkl_data/ucf_noise/augmentation_featurewise_std_normalization_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_val_pre './pkl_data/ucf_noise/ucf101_C3D_18_val_augmentation_featurewise_std_normalization_x_pre.pkl' --path_test_pre './pkl_data/ucf_noise/ucf101_C3D_18_test_augmentation_featurewise_std_normalization_x_pre.pkl' --path_x_embedding './pkl_data/ucf_noise/augmentation_featurewise_std_normalization_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_ucf101_C3D_18.csv' --save_col_name 'height_shift' --path_x './pkl_data/ucf_noise/augmentation_height_shift_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_val_pre './pkl_data/ucf_noise/ucf101_C3D_18_val_augmentation_height_shift_x_pre.pkl' --path_test_pre './pkl_data/ucf_noise/ucf101_C3D_18_test_augmentation_height_shift_x_pre.pkl' --path_x_embedding './pkl_data/ucf_noise/augmentation_height_shift_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_ucf101_C3D_18.csv' --save_col_name 'horizontal_flip' --path_x './pkl_data/ucf_noise/augmentation_horizontal_flip_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_val_pre './pkl_data/ucf_noise/ucf101_C3D_18_val_augmentation_horizontal_flip_x_pre.pkl' --path_test_pre './pkl_data/ucf_noise/ucf101_C3D_18_test_augmentation_horizontal_flip_x_pre.pkl' --path_x_embedding './pkl_data/ucf_noise/augmentation_horizontal_flip_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_ucf101_C3D_18.csv' --save_col_name 'shear_range' --path_x './pkl_data/ucf_noise/augmentation_shear_range_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_val_pre './pkl_data/ucf_noise/ucf101_C3D_18_val_augmentation_shear_range_x_pre.pkl' --path_test_pre './pkl_data/ucf_noise/ucf101_C3D_18_test_augmentation_shear_range_x_pre.pkl' --path_x_embedding './pkl_data/ucf_noise/augmentation_shear_range_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_ucf101_C3D_18.csv' --save_col_name 'width_shift' --path_x './pkl_data/ucf_noise/augmentation_width_shift_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_val_pre './pkl_data/ucf_noise/ucf101_C3D_18_val_augmentation_width_shift_x_pre.pkl' --path_test_pre './pkl_data/ucf_noise/ucf101_C3D_18_test_augmentation_width_shift_x_pre.pkl' --path_x_embedding './pkl_data/ucf_noise/augmentation_width_shift_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_ucf101_C3D_18.csv' --save_col_name 'zca_whitening' --path_x './pkl_data/ucf_noise/augmentation_zca_whitening_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_val_pre './pkl_data/ucf_noise/ucf101_C3D_18_val_augmentation_zca_whitening_x_pre.pkl' --path_test_pre './pkl_data/ucf_noise/ucf101_C3D_18_test_augmentation_zca_whitening_x_pre.pkl' --path_x_embedding './pkl_data/ucf_noise/augmentation_zca_whitening_x_embedding.pkl'

python vrank_apfd_evaluation.py --save_path_name 'apfd_ucf101_R3D_10.csv' --save_col_name 'original' --path_x './pkl_data/ucf101/ucf101_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_val_pre './target_models/ucf101_R3D_10_val_pre.pkl' --path_test_pre './target_models/ucf101_R3D_10_test_pre.pkl' --path_x_embedding './pkl_data/ucf101/ucf101_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_ucf101_R3D_10.csv' --save_col_name 'channel_shift_range' --path_x './pkl_data/ucf_noise/augmentation_channel_shift_range_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_val_pre './pkl_data/ucf_noise/ucf101_R3D_10_val_augmentation_channel_shift_range_x_pre.pkl' --path_test_pre './pkl_data/ucf_noise/ucf101_R3D_10_test_augmentation_channel_shift_range_x_pre.pkl' --path_x_embedding './pkl_data/ucf_noise/augmentation_channel_shift_range_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_ucf101_R3D_10.csv' --save_col_name 'featurewise_std_normalization' --path_x './pkl_data/ucf_noise/augmentation_featurewise_std_normalization_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_val_pre './pkl_data/ucf_noise/ucf101_R3D_10_val_augmentation_featurewise_std_normalization_x_pre.pkl' --path_test_pre './pkl_data/ucf_noise/ucf101_R3D_10_test_augmentation_featurewise_std_normalization_x_pre.pkl' --path_x_embedding './pkl_data/ucf_noise/augmentation_featurewise_std_normalization_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_ucf101_R3D_10.csv' --save_col_name 'height_shift' --path_x './pkl_data/ucf_noise/augmentation_height_shift_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_val_pre './pkl_data/ucf_noise/ucf101_R3D_10_val_augmentation_height_shift_x_pre.pkl' --path_test_pre './pkl_data/ucf_noise/ucf101_R3D_10_test_augmentation_height_shift_x_pre.pkl' --path_x_embedding './pkl_data/ucf_noise/augmentation_height_shift_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_ucf101_R3D_10.csv' --save_col_name 'horizontal_flip' --path_x './pkl_data/ucf_noise/augmentation_horizontal_flip_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_val_pre './pkl_data/ucf_noise/ucf101_R3D_10_val_augmentation_horizontal_flip_x_pre.pkl' --path_test_pre './pkl_data/ucf_noise/ucf101_R3D_10_test_augmentation_horizontal_flip_x_pre.pkl' --path_x_embedding './pkl_data/ucf_noise/augmentation_horizontal_flip_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_ucf101_R3D_10.csv' --save_col_name 'shear_range' --path_x './pkl_data/ucf_noise/augmentation_shear_range_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_val_pre './pkl_data/ucf_noise/ucf101_R3D_10_val_augmentation_shear_range_x_pre.pkl' --path_test_pre './pkl_data/ucf_noise/ucf101_R3D_10_test_augmentation_shear_range_x_pre.pkl' --path_x_embedding './pkl_data/ucf_noise/augmentation_shear_range_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_ucf101_R3D_10.csv' --save_col_name 'width_shift' --path_x './pkl_data/ucf_noise/augmentation_width_shift_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_val_pre './pkl_data/ucf_noise/ucf101_R3D_10_val_augmentation_width_shift_x_pre.pkl' --path_test_pre './pkl_data/ucf_noise/ucf101_R3D_10_test_augmentation_width_shift_x_pre.pkl' --path_x_embedding './pkl_data/ucf_noise/augmentation_width_shift_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_ucf101_R3D_10.csv' --save_col_name 'zca_whitening' --path_x './pkl_data/ucf_noise/augmentation_zca_whitening_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_val_pre './pkl_data/ucf_noise/ucf101_R3D_10_val_augmentation_zca_whitening_x_pre.pkl' --path_test_pre './pkl_data/ucf_noise/ucf101_R3D_10_test_augmentation_zca_whitening_x_pre.pkl' --path_x_embedding './pkl_data/ucf_noise/augmentation_zca_whitening_x_embedding.pkl'


python vrank_apfd_evaluation.py --save_path_name 'apfd_ucf101_R2Plus1D_21.csv' --save_col_name 'original' --path_x './pkl_data/ucf101/ucf101_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_val_pre './target_models/ucf101_R2Plus1D_21_val_pre.pkl' --path_test_pre './target_models/ucf101_R2Plus1D_21_test_pre.pkl' --path_x_embedding './pkl_data/ucf101/ucf101_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_ucf101_R2Plus1D_21.csv' --save_col_name 'channel_shift_range' --path_x './pkl_data/ucf_noise/augmentation_channel_shift_range_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_val_pre './pkl_data/ucf_noise/ucf101_R2Plus1D_21_val_augmentation_channel_shift_range_x_pre.pkl' --path_test_pre './pkl_data/ucf_noise/ucf101_R2Plus1D_21_test_augmentation_channel_shift_range_x_pre.pkl' --path_x_embedding './pkl_data/ucf_noise/augmentation_channel_shift_range_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_ucf101_R2Plus1D_21.csv' --save_col_name 'featurewise_std_normalization' --path_x './pkl_data/ucf_noise/augmentation_featurewise_std_normalization_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_val_pre './pkl_data/ucf_noise/ucf101_R2Plus1D_21_val_augmentation_featurewise_std_normalization_x_pre.pkl' --path_test_pre './pkl_data/ucf_noise/ucf101_R2Plus1D_21_test_augmentation_featurewise_std_normalization_x_pre.pkl' --path_x_embedding './pkl_data/ucf_noise/augmentation_featurewise_std_normalization_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_ucf101_R2Plus1D_21.csv' --save_col_name 'height_shift' --path_x './pkl_data/ucf_noise/augmentation_height_shift_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_val_pre './pkl_data/ucf_noise/ucf101_R2Plus1D_21_val_augmentation_height_shift_x_pre.pkl' --path_test_pre './pkl_data/ucf_noise/ucf101_R2Plus1D_21_test_augmentation_height_shift_x_pre.pkl' --path_x_embedding './pkl_data/ucf_noise/augmentation_height_shift_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_ucf101_R2Plus1D_21.csv' --save_col_name 'horizontal_flip' --path_x './pkl_data/ucf_noise/augmentation_horizontal_flip_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_val_pre './pkl_data/ucf_noise/ucf101_R2Plus1D_21_val_augmentation_horizontal_flip_x_pre.pkl' --path_test_pre './pkl_data/ucf_noise/ucf101_R2Plus1D_21_test_augmentation_horizontal_flip_x_pre.pkl' --path_x_embedding './pkl_data/ucf_noise/augmentation_horizontal_flip_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_ucf101_R2Plus1D_21.csv' --save_col_name 'shear_range' --path_x './pkl_data/ucf_noise/augmentation_shear_range_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_val_pre './pkl_data/ucf_noise/ucf101_R2Plus1D_21_val_augmentation_shear_range_x_pre.pkl' --path_test_pre './pkl_data/ucf_noise/ucf101_R2Plus1D_21_test_augmentation_shear_range_x_pre.pkl' --path_x_embedding './pkl_data/ucf_noise/augmentation_shear_range_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_ucf101_R2Plus1D_21.csv' --save_col_name 'width_shift' --path_x './pkl_data/ucf_noise/augmentation_width_shift_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_val_pre './pkl_data/ucf_noise/ucf101_R2Plus1D_21_val_augmentation_width_shift_x_pre.pkl' --path_test_pre './pkl_data/ucf_noise/ucf101_R2Plus1D_21_test_augmentation_width_shift_x_pre.pkl' --path_x_embedding './pkl_data/ucf_noise/augmentation_width_shift_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_ucf101_R2Plus1D_21.csv' --save_col_name 'zca_whitening' --path_x './pkl_data/ucf_noise/augmentation_zca_whitening_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_val_pre './pkl_data/ucf_noise/ucf101_R2Plus1D_21_val_augmentation_zca_whitening_x_pre.pkl' --path_test_pre './pkl_data/ucf_noise/ucf101_R2Plus1D_21_test_augmentation_zca_whitening_x_pre.pkl' --path_x_embedding './pkl_data/ucf_noise/augmentation_zca_whitening_x_embedding.pkl'


python vrank_apfd_evaluation.py --save_path_name 'apfd_ucf101_slowfastnet_24.csv' --save_col_name 'original' --path_x './pkl_data/ucf101/ucf101_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_val_pre './target_models/ucf101_slowfastnet_24_val_pre.pkl' --path_test_pre './target_models/ucf101_slowfastnet_24_test_pre.pkl' --path_x_embedding './pkl_data/ucf101/ucf101_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_ucf101_slowfastnet_24.csv' --save_col_name 'channel_shift_range' --path_x './pkl_data/ucf_noise/augmentation_channel_shift_range_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_val_pre './pkl_data/ucf_noise/ucf101_slowfastnet_24_val_augmentation_channel_shift_range_x_pre.pkl' --path_test_pre './pkl_data/ucf_noise/ucf101_slowfastnet_24_test_augmentation_channel_shift_range_x_pre.pkl' --path_x_embedding './pkl_data/ucf_noise/augmentation_channel_shift_range_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_ucf101_slowfastnet_24.csv' --save_col_name 'featurewise_std_normalization' --path_x './pkl_data/ucf_noise/augmentation_featurewise_std_normalization_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_val_pre './pkl_data/ucf_noise/ucf101_slowfastnet_24_val_augmentation_featurewise_std_normalization_x_pre.pkl' --path_test_pre './pkl_data/ucf_noise/ucf101_slowfastnet_24_test_augmentation_featurewise_std_normalization_x_pre.pkl' --path_x_embedding './pkl_data/ucf_noise/augmentation_featurewise_std_normalization_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_ucf101_slowfastnet_24.csv' --save_col_name 'height_shift' --path_x './pkl_data/ucf_noise/augmentation_height_shift_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_val_pre './pkl_data/ucf_noise/ucf101_slowfastnet_24_val_augmentation_height_shift_x_pre.pkl' --path_test_pre './pkl_data/ucf_noise/ucf101_slowfastnet_24_test_augmentation_height_shift_x_pre.pkl' --path_x_embedding './pkl_data/ucf_noise/augmentation_height_shift_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_ucf101_slowfastnet_24.csv' --save_col_name 'horizontal_flip' --path_x './pkl_data/ucf_noise/augmentation_horizontal_flip_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_val_pre './pkl_data/ucf_noise/ucf101_slowfastnet_24_val_augmentation_horizontal_flip_x_pre.pkl' --path_test_pre './pkl_data/ucf_noise/ucf101_slowfastnet_24_test_augmentation_horizontal_flip_x_pre.pkl' --path_x_embedding './pkl_data/ucf_noise/augmentation_horizontal_flip_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_ucf101_slowfastnet_24.csv' --save_col_name 'shear_range' --path_x './pkl_data/ucf_noise/augmentation_shear_range_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_val_pre './pkl_data/ucf_noise/ucf101_slowfastnet_24_val_augmentation_shear_range_x_pre.pkl' --path_test_pre './pkl_data/ucf_noise/ucf101_slowfastnet_24_test_augmentation_shear_range_x_pre.pkl' --path_x_embedding './pkl_data/ucf_noise/augmentation_shear_range_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_ucf101_slowfastnet_24.csv' --save_col_name 'width_shift' --path_x './pkl_data/ucf_noise/augmentation_width_shift_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_val_pre './pkl_data/ucf_noise/ucf101_slowfastnet_24_val_augmentation_width_shift_x_pre.pkl' --path_test_pre './pkl_data/ucf_noise/ucf101_slowfastnet_24_test_augmentation_width_shift_x_pre.pkl' --path_x_embedding './pkl_data/ucf_noise/augmentation_width_shift_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_ucf101_slowfastnet_24.csv' --save_col_name 'zca_whitening' --path_x './pkl_data/ucf_noise/augmentation_zca_whitening_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_val_pre './pkl_data/ucf_noise/ucf101_slowfastnet_24_val_augmentation_zca_whitening_x_pre.pkl' --path_test_pre './pkl_data/ucf_noise/ucf101_slowfastnet_24_test_augmentation_zca_whitening_x_pre.pkl' --path_x_embedding './pkl_data/ucf_noise/augmentation_zca_whitening_x_embedding.pkl'

#######################################

python vrank_apfd_evaluation.py --save_path_name 'apfd_hmdb51_C3D_40.csv' --save_col_name 'original' --path_x './pkl_data/hmdb51/hmdb51_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl' --path_val_pre './target_models/hmdb51_C3D_40_val_pre.pkl' --path_test_pre './target_models/hmdb51_C3D_40_test_pre.pkl' --path_x_embedding './pkl_data/hmdb51/hmdb51_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_hmdb51_C3D_40.csv' --save_col_name 'channel_shift_range' --path_x './pkl_data/hmdb_noise/augmentation_channel_shift_range_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl' --path_val_pre './pkl_data/hmdb_noise/hmdb51_C3D_40_val_augmentation_channel_shift_range_x_pre.pkl' --path_test_pre './pkl_data/hmdb_noise/hmdb51_C3D_40_test_augmentation_channel_shift_range_x_pre.pkl' --path_x_embedding './pkl_data/hmdb_noise/augmentation_channel_shift_range_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_hmdb51_C3D_40.csv' --save_col_name 'featurewise_std_normalization' --path_x './pkl_data/hmdb_noise/augmentation_featurewise_std_normalization_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl' --path_val_pre './pkl_data/hmdb_noise/hmdb51_C3D_40_val_augmentation_featurewise_std_normalization_x_pre.pkl' --path_test_pre './pkl_data/hmdb_noise/hmdb51_C3D_40_test_augmentation_featurewise_std_normalization_x_pre.pkl' --path_x_embedding './pkl_data/hmdb_noise/augmentation_featurewise_std_normalization_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_hmdb51_C3D_40.csv' --save_col_name 'height_shift' --path_x './pkl_data/hmdb_noise/augmentation_height_shift_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl' --path_val_pre './pkl_data/hmdb_noise/hmdb51_C3D_40_val_augmentation_height_shift_x_pre.pkl' --path_test_pre './pkl_data/hmdb_noise/hmdb51_C3D_40_test_augmentation_height_shift_x_pre.pkl' --path_x_embedding './pkl_data/hmdb_noise/augmentation_height_shift_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_hmdb51_C3D_40.csv' --save_col_name 'horizontal_flip' --path_x './pkl_data/hmdb_noise/augmentation_horizontal_flip_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl' --path_val_pre './pkl_data/hmdb_noise/hmdb51_C3D_40_val_augmentation_horizontal_flip_x_pre.pkl' --path_test_pre './pkl_data/hmdb_noise/hmdb51_C3D_40_test_augmentation_horizontal_flip_x_pre.pkl' --path_x_embedding './pkl_data/hmdb_noise/augmentation_horizontal_flip_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_hmdb51_C3D_40.csv' --save_col_name 'shear_range' --path_x './pkl_data/hmdb_noise/augmentation_shear_range_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl' --path_val_pre './pkl_data/hmdb_noise/hmdb51_C3D_40_val_augmentation_shear_range_x_pre.pkl' --path_test_pre './pkl_data/hmdb_noise/hmdb51_C3D_40_test_augmentation_shear_range_x_pre.pkl' --path_x_embedding './pkl_data/hmdb_noise/augmentation_shear_range_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_hmdb51_C3D_40.csv' --save_col_name 'width_shift' --path_x './pkl_data/hmdb_noise/augmentation_width_shift_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl' --path_val_pre './pkl_data/hmdb_noise/hmdb51_C3D_40_val_augmentation_width_shift_x_pre.pkl' --path_test_pre './pkl_data/hmdb_noise/hmdb51_C3D_40_test_augmentation_width_shift_x_pre.pkl' --path_x_embedding './pkl_data/hmdb_noise/augmentation_width_shift_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_hmdb51_C3D_40.csv' --save_col_name 'zca_whitening' --path_x './pkl_data/hmdb_noise/augmentation_zca_whitening_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl' --path_val_pre './pkl_data/hmdb_noise/hmdb51_C3D_40_val_augmentation_zca_whitening_x_pre.pkl' --path_test_pre './pkl_data/hmdb_noise/hmdb51_C3D_40_test_augmentation_zca_whitening_x_pre.pkl' --path_x_embedding './pkl_data/hmdb_noise/augmentation_zca_whitening_x_embedding.pkl'


python vrank_apfd_evaluation.py --save_path_name 'apfd_hmdb51_R3D_40.csv' --save_col_name 'original' --path_x './pkl_data/hmdb51/hmdb51_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl' --path_val_pre './target_models/hmdb51_R3D_40_val_pre.pkl' --path_test_pre './target_models/hmdb51_R3D_40_test_pre.pkl' --path_x_embedding './pkl_data/hmdb51/hmdb51_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_hmdb51_R3D_40.csv' --save_col_name 'channel_shift_range' --path_x './pkl_data/hmdb_noise/augmentation_channel_shift_range_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl' --path_val_pre './pkl_data/hmdb_noise/hmdb51_R3D_40_val_augmentation_channel_shift_range_x_pre.pkl' --path_test_pre './pkl_data/hmdb_noise/hmdb51_R3D_40_test_augmentation_channel_shift_range_x_pre.pkl' --path_x_embedding './pkl_data/hmdb_noise/augmentation_channel_shift_range_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_hmdb51_R3D_40.csv' --save_col_name 'featurewise_std_normalization' --path_x './pkl_data/hmdb_noise/augmentation_featurewise_std_normalization_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl' --path_val_pre './pkl_data/hmdb_noise/hmdb51_R3D_40_val_augmentation_featurewise_std_normalization_x_pre.pkl' --path_test_pre './pkl_data/hmdb_noise/hmdb51_R3D_40_test_augmentation_featurewise_std_normalization_x_pre.pkl' --path_x_embedding './pkl_data/hmdb_noise/augmentation_featurewise_std_normalization_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_hmdb51_R3D_40.csv' --save_col_name 'height_shift' --path_x './pkl_data/hmdb_noise/augmentation_height_shift_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl' --path_val_pre './pkl_data/hmdb_noise/hmdb51_R3D_40_val_augmentation_height_shift_x_pre.pkl' --path_test_pre './pkl_data/hmdb_noise/hmdb51_R3D_40_test_augmentation_height_shift_x_pre.pkl' --path_x_embedding './pkl_data/hmdb_noise/augmentation_height_shift_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_hmdb51_R3D_40.csv' --save_col_name 'horizontal_flip' --path_x './pkl_data/hmdb_noise/augmentation_horizontal_flip_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl' --path_val_pre './pkl_data/hmdb_noise/hmdb51_R3D_40_val_augmentation_horizontal_flip_x_pre.pkl' --path_test_pre './pkl_data/hmdb_noise/hmdb51_R3D_40_test_augmentation_horizontal_flip_x_pre.pkl' --path_x_embedding './pkl_data/hmdb_noise/augmentation_horizontal_flip_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_hmdb51_R3D_40.csv' --save_col_name 'shear_range' --path_x './pkl_data/hmdb_noise/augmentation_shear_range_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl' --path_val_pre './pkl_data/hmdb_noise/hmdb51_R3D_40_val_augmentation_shear_range_x_pre.pkl' --path_test_pre './pkl_data/hmdb_noise/hmdb51_R3D_40_test_augmentation_shear_range_x_pre.pkl' --path_x_embedding './pkl_data/hmdb_noise/augmentation_shear_range_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_hmdb51_R3D_40.csv' --save_col_name 'width_shift' --path_x './pkl_data/hmdb_noise/augmentation_width_shift_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl' --path_val_pre './pkl_data/hmdb_noise/hmdb51_R3D_40_val_augmentation_width_shift_x_pre.pkl' --path_test_pre './pkl_data/hmdb_noise/hmdb51_R3D_40_test_augmentation_width_shift_x_pre.pkl' --path_x_embedding './pkl_data/hmdb_noise/augmentation_width_shift_x_embedding.pkl'
python vrank_apfd_evaluation.py --save_path_name 'apfd_hmdb51_R3D_40.csv' --save_col_name 'zca_whitening' --path_x './pkl_data/hmdb_noise/augmentation_zca_whitening_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl' --path_val_pre './pkl_data/hmdb_noise/hmdb51_R3D_40_val_augmentation_zca_whitening_x_pre.pkl' --path_test_pre './pkl_data/hmdb_noise/hmdb51_R3D_40_test_augmentation_zca_whitening_x_pre.pkl' --path_x_embedding './pkl_data/hmdb_noise/augmentation_zca_whitening_x_embedding.pkl'




