python video_model_train.py --cuda 'cuda:2' --model_name 'C3D' --epochs 101 --data_name 'charades' --path_x '/raid/yinghua/VRank/data/pkl_data/charades/charades_x.pkl' --path_y '/raid/yinghua/VRank/data/pkl_data/charades/charades_y.pkl' --batch_size 24 --save_model_path './target_models/charades_C3D'
python video_model_train.py --cuda 'cuda:2' --model_name 'R3D' --epochs 101 --data_name 'charades' --path_x '/raid/yinghua/VRank/data/pkl_data/charades/charades_x.pkl' --path_y '/raid/yinghua/VRank/data/pkl_data/charades/charades_y.pkl' --batch_size 24 --save_model_path './target_models/charades_R3D'
python video_model_train.py --cuda 'cuda:2' --model_name 'R2Plus1D' --epochs 101 --data_name 'charades' --path_x '/raid/yinghua/VRank/data/pkl_data/charades/charades_x.pkl' --path_y '/raid/yinghua/VRank/data/pkl_data/charades/charades_y.pkl' --batch_size 24 --save_model_path './target_models/charades_R2Plus1D'
python video_model_train.py --cuda 'cuda:2' --model_name 'slowfastnet' --epochs 101 --data_name 'charades' --path_x '/raid/yinghua/VRank/data/pkl_data/charades/charades_x.pkl' --path_y '/raid/yinghua/VRank/data/pkl_data/charades/charades_y.pkl' --batch_size 24 --save_model_path './target_models/charades_slowfastnet'

python video_model_train.py --cuda 'cuda:2' --model_name 'C3D' --epochs 101 --data_name 'hmdb51' --path_x '/raid/yinghua/VRank/data/pkl_data/hmdb51/hmdb51_x.pkl' --path_y '/raid/yinghua/VRank/data/pkl_data/hmdb51/hmdb51_y.pkl' --batch_size 24 --save_model_path './target_models/hmdb51_C3D'
python video_model_train.py --cuda 'cuda:2' --model_name 'R3D' --epochs 101 --data_name 'hmdb51' --path_x '/raid/yinghua/VRank/data/pkl_data/hmdb51/hmdb51_x.pkl' --path_y '/raid/yinghua/VRank/data/pkl_data/hmdb51/hmdb51_y.pkl' --batch_size 24 --save_model_path './target_models/hmdb51_R3D'
python video_model_train.py --cuda 'cuda:2' --model_name 'R2Plus1D' --epochs 101 --data_name 'hmdb51' --path_x '/raid/yinghua/VRank/data/pkl_data/hmdb51/hmdb51_x.pkl' --path_y '/raid/yinghua/VRank/data/pkl_data/hmdb51/hmdb51_y.pkl' --batch_size 24 --save_model_path './target_models/hmdb51_R2Plus1D'
python video_model_train.py --cuda 'cuda:2' --model_name 'slowfastnet' --epochs 101 --data_name 'hmdb51' --path_x '/raid/yinghua/VRank/data/pkl_data/hmdb51/hmdb51_x.pkl' --path_y '/raid/yinghua/VRank/data/pkl_data/hmdb51/hmdb51_y.pkl' --batch_size 24 --save_model_path './target_models/hmdb51_slowfastnet'

python video_model_train.py --cuda 'cuda:2' --model_name 'C3D' --epochs 51 --data_name 'hollywood2' --path_x '/raid/yinghua/VRank/data/pkl_data/hollywood2/hollywood2_x.pkl' --path_y '/raid/yinghua/VRank/data/pkl_data/hollywood2/hollywood2_y.pkl' --batch_size 24 --save_model_path './target_models/hollywood2_C3D'
python video_model_train.py --cuda 'cuda:2' --model_name 'R3D' --epochs 51 --data_name 'hollywood2' --path_x '/raid/yinghua/VRank/data/pkl_data/hollywood2/hollywood2_x.pkl' --path_y '/raid/yinghua/VRank/data/pkl_data/hollywood2/hollywood2_y.pkl' --batch_size 24 --save_model_path './target_models/hollywood2_R3D'
python video_model_train.py --cuda 'cuda:2' --model_name 'R2Plus1D' --epochs 51 --data_name 'hollywood2' --path_x '/raid/yinghua/VRank/data/pkl_data/hollywood2/hollywood2_x.pkl' --path_y '/raid/yinghua/VRank/data/pkl_data/hollywood2/hollywood2_y.pkl' --batch_size 24 --save_model_path './target_models/hollywood2_R2Plus1D'
python video_model_train.py --cuda 'cuda:2' --model_name 'slowfastnet' --epochs 51 --data_name 'hollywood2' --path_x '/raid/yinghua/VRank/data/pkl_data/hollywood2/hollywood2_x.pkl' --path_y '/raid/yinghua/VRank/data/pkl_data/hollywood2/hollywood2_y.pkl' --batch_size 24 --save_model_path './target_models/hollywood2_slowfastnet'

python video_model_train.py --cuda 'cuda:0' --model_name 'C3D' --epochs 51 --data_name 'accident' --path_x '/raid/yinghua/VRank/data/pkl_data/accident/accident_x.pkl' --path_y '/raid/yinghua/VRank/data/pkl_data/accident/accident_y.pkl' --batch_size 24 --save_model_path './target_models/accident_C3D'
python video_model_train.py --cuda 'cuda:0' --model_name 'R3D' --epochs 51 --data_name 'accident' --path_x '/raid/yinghua/VRank/data/pkl_data/accident/accident_x.pkl' --path_y '/raid/yinghua/VRank/data/pkl_data/accident/accident_y.pkl' --batch_size 24 --save_model_path './target_models/accident_R3D'
python video_model_train.py --cuda 'cuda:0' --model_name 'R2Plus1D' --epochs 51 --data_name 'accident' --path_x '/raid/yinghua/VRank/data/pkl_data/accident/accident_x.pkl' --path_y '/raid/yinghua/VRank/data/pkl_data/accident/accident_y.pkl' --batch_size 24 --save_model_path './target_models/accident_R2Plus1D'
python video_model_train.py --cuda 'cuda:0' --model_name 'slowfastnet' --epochs 51 --data_name 'accident' --path_x '/raid/yinghua/VRank/data/pkl_data/accident/accident_x.pkl' --path_y '/raid/yinghua/VRank/data/pkl_data/accident/accident_y.pkl' --batch_size 24 --save_model_path './target_models/accident_slowfastnet'


