python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/ucf_noise/augmentation_channel_shift_range_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl'  --model_path './target_models/ucf101_C3D_18.pt' --save_val_vec './pkl_data/ucf_noise/ucf101_C3D_18_val_augmentation_channel_shift_range_x_pre.pkl' --save_test_vec './pkl_data/ucf_noise/ucf101_C3D_18_test_augmentation_channel_shift_range_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/ucf_noise/augmentation_featurewise_std_normalization_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl'  --model_path './target_models/ucf101_C3D_18.pt' --save_val_vec './pkl_data/ucf_noise/ucf101_C3D_18_val_augmentation_featurewise_std_normalization_x_pre.pkl' --save_test_vec './pkl_data/ucf_noise/ucf101_C3D_18_test_augmentation_featurewise_std_normalization_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/ucf_noise/augmentation_height_shift_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl'  --model_path './target_models/ucf101_C3D_18.pt' --save_val_vec './pkl_data/ucf_noise/ucf101_C3D_18_val_augmentation_height_shift_x_pre.pkl' --save_test_vec './pkl_data/ucf_noise/ucf101_C3D_18_test_augmentation_height_shift_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/ucf_noise/augmentation_horizontal_flip_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl'  --model_path './target_models/ucf101_C3D_18.pt' --save_val_vec './pkl_data/ucf_noise/ucf101_C3D_18_val_augmentation_horizontal_flip_x_pre.pkl' --save_test_vec './pkl_data/ucf_noise/ucf101_C3D_18_test_augmentation_horizontal_flip_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/ucf_noise/augmentation_shear_range_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl'  --model_path './target_models/ucf101_C3D_18.pt' --save_val_vec './pkl_data/ucf_noise/ucf101_C3D_18_val_augmentation_shear_range_x_pre.pkl' --save_test_vec './pkl_data/ucf_noise/ucf101_C3D_18_test_augmentation_shear_range_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/ucf_noise/augmentation_width_shift_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl'  --model_path './target_models/ucf101_C3D_18.pt' --save_val_vec './pkl_data/ucf_noise/ucf101_C3D_18_val_augmentation_width_shift_x_pre.pkl' --save_test_vec './pkl_data/ucf_noise/ucf101_C3D_18_test_augmentation_width_shift_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/ucf_noise/augmentation_zca_whitening_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl'  --model_path './target_models/ucf101_C3D_18.pt' --save_val_vec './pkl_data/ucf_noise/ucf101_C3D_18_val_augmentation_zca_whitening_x_pre.pkl' --save_test_vec './pkl_data/ucf_noise/ucf101_C3D_18_test_augmentation_zca_whitening_x_pre.pkl'


python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/ucf_noise/augmentation_channel_shift_range_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl'  --model_path './target_models/ucf101_R3D_30.pt' --save_val_vec './pkl_data/ucf_noise/ucf101_R3D_30_val_augmentation_channel_shift_range_x_pre.pkl' --save_test_vec './pkl_data/ucf_noise/ucf101_R3D_30_test_augmentation_channel_shift_range_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/ucf_noise/augmentation_featurewise_std_normalization_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl'  --model_path './target_models/ucf101_R3D_30.pt' --save_val_vec './pkl_data/ucf_noise/ucf101_R3D_30_val_augmentation_featurewise_std_normalization_x_pre.pkl' --save_test_vec './pkl_data/ucf_noise/ucf101_R3D_30_test_augmentation_featurewise_std_normalization_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/ucf_noise/augmentation_height_shift_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl'  --model_path './target_models/ucf101_R3D_30.pt' --save_val_vec './pkl_data/ucf_noise/ucf101_R3D_30_val_augmentation_height_shift_x_pre.pkl' --save_test_vec './pkl_data/ucf_noise/ucf101_R3D_30_test_augmentation_height_shift_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/ucf_noise/augmentation_horizontal_flip_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl'  --model_path './target_models/ucf101_R3D_30.pt' --save_val_vec './pkl_data/ucf_noise/ucf101_R3D_30_val_augmentation_horizontal_flip_x_pre.pkl' --save_test_vec './pkl_data/ucf_noise/ucf101_R3D_30_test_augmentation_horizontal_flip_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/ucf_noise/augmentation_shear_range_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl'  --model_path './target_models/ucf101_R3D_30.pt' --save_val_vec './pkl_data/ucf_noise/ucf101_R3D_30_val_augmentation_shear_range_x_pre.pkl' --save_test_vec './pkl_data/ucf_noise/ucf101_R3D_30_test_augmentation_shear_range_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/ucf_noise/augmentation_width_shift_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl'  --model_path './target_models/ucf101_R3D_30.pt' --save_val_vec './pkl_data/ucf_noise/ucf101_R3D_30_val_augmentation_width_shift_x_pre.pkl' --save_test_vec './pkl_data/ucf_noise/ucf101_R3D_30_test_augmentation_width_shift_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/ucf_noise/augmentation_zca_whitening_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl'  --model_path './target_models/ucf101_R3D_30.pt' --save_val_vec './pkl_data/ucf_noise/ucf101_R3D_30_val_augmentation_zca_whitening_x_pre.pkl' --save_test_vec './pkl_data/ucf_noise/ucf101_R3D_30_test_augmentation_zca_whitening_x_pre.pkl'


python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/ucf_noise/augmentation_channel_shift_range_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl'  --model_path './target_models/ucf101_R2Plus1D_21.pt' --save_val_vec './pkl_data/ucf_noise/ucf101_R2Plus1D_21_val_augmentation_channel_shift_range_x_pre.pkl' --save_test_vec './pkl_data/ucf_noise/ucf101_R2Plus1D_21_test_augmentation_channel_shift_range_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/ucf_noise/augmentation_featurewise_std_normalization_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl'  --model_path './target_models/ucf101_R2Plus1D_21.pt' --save_val_vec './pkl_data/ucf_noise/ucf101_R2Plus1D_21_val_augmentation_featurewise_std_normalization_x_pre.pkl' --save_test_vec './pkl_data/ucf_noise/ucf101_R2Plus1D_21_test_augmentation_featurewise_std_normalization_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/ucf_noise/augmentation_height_shift_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl'  --model_path './target_models/ucf101_R2Plus1D_21.pt' --save_val_vec './pkl_data/ucf_noise/ucf101_R2Plus1D_21_val_augmentation_height_shift_x_pre.pkl' --save_test_vec './pkl_data/ucf_noise/ucf101_R2Plus1D_21_test_augmentation_height_shift_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/ucf_noise/augmentation_horizontal_flip_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl'  --model_path './target_models/ucf101_R2Plus1D_21.pt' --save_val_vec './pkl_data/ucf_noise/ucf101_R2Plus1D_21_val_augmentation_horizontal_flip_x_pre.pkl' --save_test_vec './pkl_data/ucf_noise/ucf101_R2Plus1D_21_test_augmentation_horizontal_flip_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/ucf_noise/augmentation_shear_range_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl'  --model_path './target_models/ucf101_R2Plus1D_21.pt' --save_val_vec './pkl_data/ucf_noise/ucf101_R2Plus1D_21_val_augmentation_shear_range_x_pre.pkl' --save_test_vec './pkl_data/ucf_noise/ucf101_R2Plus1D_21_test_augmentation_shear_range_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/ucf_noise/augmentation_width_shift_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl'  --model_path './target_models/ucf101_R2Plus1D_21.pt' --save_val_vec './pkl_data/ucf_noise/ucf101_R2Plus1D_21_val_augmentation_width_shift_x_pre.pkl' --save_test_vec './pkl_data/ucf_noise/ucf101_R2Plus1D_21_test_augmentation_width_shift_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/ucf_noise/augmentation_zca_whitening_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl'  --model_path './target_models/ucf101_R2Plus1D_21.pt' --save_val_vec './pkl_data/ucf_noise/ucf101_R2Plus1D_21_val_augmentation_zca_whitening_x_pre.pkl' --save_test_vec './pkl_data/ucf_noise/ucf101_R2Plus1D_21_test_augmentation_zca_whitening_x_pre.pkl'


python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/ucf_noise/augmentation_channel_shift_range_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl'  --model_path './target_models/ucf101_slowfastnet_24.pt' --save_val_vec './pkl_data/ucf_noise/ucf101_slowfastnet_24_val_augmentation_channel_shift_range_x_pre.pkl' --save_test_vec './pkl_data/ucf_noise/ucf101_slowfastnet_24_test_augmentation_channel_shift_range_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/ucf_noise/augmentation_featurewise_std_normalization_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl'  --model_path './target_models/ucf101_slowfastnet_24.pt' --save_val_vec './pkl_data/ucf_noise/ucf101_slowfastnet_24_val_augmentation_featurewise_std_normalization_x_pre.pkl' --save_test_vec './pkl_data/ucf_noise/ucf101_slowfastnet_24_test_augmentation_featurewise_std_normalization_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/ucf_noise/augmentation_height_shift_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl'  --model_path './target_models/ucf101_slowfastnet_24.pt' --save_val_vec './pkl_data/ucf_noise/ucf101_slowfastnet_24_val_augmentation_height_shift_x_pre.pkl' --save_test_vec './pkl_data/ucf_noise/ucf101_slowfastnet_24_test_augmentation_height_shift_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/ucf_noise/augmentation_horizontal_flip_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl'  --model_path './target_models/ucf101_slowfastnet_24.pt' --save_val_vec './pkl_data/ucf_noise/ucf101_slowfastnet_24_val_augmentation_horizontal_flip_x_pre.pkl' --save_test_vec './pkl_data/ucf_noise/ucf101_slowfastnet_24_test_augmentation_horizontal_flip_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/ucf_noise/augmentation_shear_range_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl'  --model_path './target_models/ucf101_slowfastnet_24.pt' --save_val_vec './pkl_data/ucf_noise/ucf101_slowfastnet_24_val_augmentation_shear_range_x_pre.pkl' --save_test_vec './pkl_data/ucf_noise/ucf101_slowfastnet_24_test_augmentation_shear_range_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/ucf_noise/augmentation_width_shift_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl'  --model_path './target_models/ucf101_slowfastnet_24.pt' --save_val_vec './pkl_data/ucf_noise/ucf101_slowfastnet_24_val_augmentation_width_shift_x_pre.pkl' --save_test_vec './pkl_data/ucf_noise/ucf101_slowfastnet_24_test_augmentation_width_shift_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/ucf_noise/augmentation_zca_whitening_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl'  --model_path './target_models/ucf101_slowfastnet_24.pt' --save_val_vec './pkl_data/ucf_noise/ucf101_slowfastnet_24_val_augmentation_zca_whitening_x_pre.pkl' --save_test_vec './pkl_data/ucf_noise/ucf101_slowfastnet_24_test_augmentation_zca_whitening_x_pre.pkl'

##############################################################################

python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/hmdb_noise/augmentation_channel_shift_range_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl'  --model_path './target_models/hmdb51_C3D_40.pt' --save_val_vec './pkl_data/hmdb_noise/hmdb51_C3D_40_val_augmentation_channel_shift_range_x_pre.pkl' --save_test_vec './pkl_data/hmdb_noise/hmdb51_C3D_40_test_augmentation_channel_shift_range_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/hmdb_noise/augmentation_featurewise_std_normalization_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl'  --model_path './target_models/hmdb51_C3D_40.pt' --save_val_vec './pkl_data/hmdb_noise/hmdb51_C3D_40_val_augmentation_featurewise_std_normalization_x_pre.pkl' --save_test_vec './pkl_data/hmdb_noise/hmdb51_C3D_40_test_augmentation_featurewise_std_normalization_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/hmdb_noise/augmentation_height_shift_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl'  --model_path './target_models/hmdb51_C3D_40.pt' --save_val_vec './pkl_data/hmdb_noise/hmdb51_C3D_40_val_augmentation_height_shift_x_pre.pkl' --save_test_vec './pkl_data/hmdb_noise/hmdb51_C3D_40_test_augmentation_height_shift_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/hmdb_noise/augmentation_horizontal_flip_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl'  --model_path './target_models/hmdb51_C3D_40.pt' --save_val_vec './pkl_data/hmdb_noise/hmdb51_C3D_40_val_augmentation_horizontal_flip_x_pre.pkl' --save_test_vec './pkl_data/hmdb_noise/hmdb51_C3D_40_test_augmentation_horizontal_flip_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/hmdb_noise/augmentation_shear_range_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl'  --model_path './target_models/hmdb51_C3D_40.pt' --save_val_vec './pkl_data/hmdb_noise/hmdb51_C3D_40_val_augmentation_shear_range_x_pre.pkl' --save_test_vec './pkl_data/hmdb_noise/hmdb51_C3D_40_test_augmentation_shear_range_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/hmdb_noise/augmentation_width_shift_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl'  --model_path './target_models/hmdb51_C3D_40.pt' --save_val_vec './pkl_data/hmdb_noise/hmdb51_C3D_40_val_augmentation_width_shift_x_pre.pkl' --save_test_vec './pkl_data/hmdb_noise/hmdb51_C3D_40_test_augmentation_width_shift_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/hmdb_noise/augmentation_zca_whitening_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl'  --model_path './target_models/hmdb51_C3D_40.pt' --save_val_vec './pkl_data/hmdb_noise/hmdb51_C3D_40_val_augmentation_zca_whitening_x_pre.pkl' --save_test_vec './pkl_data/hmdb_noise/hmdb51_C3D_40_test_augmentation_zca_whitening_x_pre.pkl'


python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/hmdb_noise/augmentation_channel_shift_range_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl'  --model_path './target_models/hmdb51_R3D_40.pt' --save_val_vec './pkl_data/hmdb_noise/hmdb51_R3D_40_val_augmentation_channel_shift_range_x_pre.pkl' --save_test_vec './pkl_data/hmdb_noise/hmdb51_R3D_40_test_augmentation_channel_shift_range_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/hmdb_noise/augmentation_featurewise_std_normalization_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl'  --model_path './target_models/hmdb51_R3D_40.pt' --save_val_vec './pkl_data/hmdb_noise/hmdb51_R3D_40_val_augmentation_featurewise_std_normalization_x_pre.pkl' --save_test_vec './pkl_data/hmdb_noise/hmdb51_R3D_40_test_augmentation_featurewise_std_normalization_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/hmdb_noise/augmentation_height_shift_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl'  --model_path './target_models/hmdb51_R3D_40.pt' --save_val_vec './pkl_data/hmdb_noise/hmdb51_R3D_40_val_augmentation_height_shift_x_pre.pkl' --save_test_vec './pkl_data/hmdb_noise/hmdb51_R3D_40_test_augmentation_height_shift_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/hmdb_noise/augmentation_horizontal_flip_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl'  --model_path './target_models/hmdb51_R3D_40.pt' --save_val_vec './pkl_data/hmdb_noise/hmdb51_R3D_40_val_augmentation_horizontal_flip_x_pre.pkl' --save_test_vec './pkl_data/hmdb_noise/hmdb51_R3D_40_test_augmentation_horizontal_flip_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/hmdb_noise/augmentation_shear_range_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl'  --model_path './target_models/hmdb51_R3D_40.pt' --save_val_vec './pkl_data/hmdb_noise/hmdb51_R3D_40_val_augmentation_shear_range_x_pre.pkl' --save_test_vec './pkl_data/hmdb_noise/hmdb51_R3D_40_test_augmentation_shear_range_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/hmdb_noise/augmentation_width_shift_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl'  --model_path './target_models/hmdb51_R3D_40.pt' --save_val_vec './pkl_data/hmdb_noise/hmdb51_R3D_40_val_augmentation_width_shift_x_pre.pkl' --save_test_vec './pkl_data/hmdb_noise/hmdb51_R3D_40_test_augmentation_width_shift_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/hmdb_noise/augmentation_zca_whitening_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl'  --model_path './target_models/hmdb51_R3D_40.pt' --save_val_vec './pkl_data/hmdb_noise/hmdb51_R3D_40_val_augmentation_zca_whitening_x_pre.pkl' --save_test_vec './pkl_data/hmdb_noise/hmdb51_R3D_40_test_augmentation_zca_whitening_x_pre.pkl'


python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/hmdb_noise/augmentation_channel_shift_range_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl'  --model_path './target_models/hmdb51_slowfastnet_40.pt' --save_val_vec './pkl_data/hmdb_noise/hmdb51_slowfastnet_40_val_augmentation_channel_shift_range_x_pre.pkl' --save_test_vec './pkl_data/hmdb_noise/hmdb51_slowfastnet_40_test_augmentation_channel_shift_range_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/hmdb_noise/augmentation_featurewise_std_normalization_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl'  --model_path './target_models/hmdb51_slowfastnet_40.pt' --save_val_vec './pkl_data/hmdb_noise/hmdb51_slowfastnet_40_val_augmentation_featurewise_std_normalization_x_pre.pkl' --save_test_vec './pkl_data/hmdb_noise/hmdb51_slowfastnet_40_test_augmentation_featurewise_std_normalization_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/hmdb_noise/augmentation_height_shift_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl'  --model_path './target_models/hmdb51_slowfastnet_40.pt' --save_val_vec './pkl_data/hmdb_noise/hmdb51_slowfastnet_40_val_augmentation_height_shift_x_pre.pkl' --save_test_vec './pkl_data/hmdb_noise/hmdb51_slowfastnet_40_test_augmentation_height_shift_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/hmdb_noise/augmentation_horizontal_flip_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl'  --model_path './target_models/hmdb51_slowfastnet_40.pt' --save_val_vec './pkl_data/hmdb_noise/hmdb51_slowfastnet_40_val_augmentation_horizontal_flip_x_pre.pkl' --save_test_vec './pkl_data/hmdb_noise/hmdb51_slowfastnet_40_test_augmentation_horizontal_flip_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/hmdb_noise/augmentation_shear_range_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl'  --model_path './target_models/hmdb51_slowfastnet_40.pt' --save_val_vec './pkl_data/hmdb_noise/hmdb51_slowfastnet_40_val_augmentation_shear_range_x_pre.pkl' --save_test_vec './pkl_data/hmdb_noise/hmdb51_slowfastnet_40_test_augmentation_shear_range_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/hmdb_noise/augmentation_width_shift_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl'  --model_path './target_models/hmdb51_slowfastnet_40.pt' --save_val_vec './pkl_data/hmdb_noise/hmdb51_slowfastnet_40_val_augmentation_width_shift_x_pre.pkl' --save_test_vec './pkl_data/hmdb_noise/hmdb51_slowfastnet_40_test_augmentation_width_shift_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/hmdb_noise/augmentation_zca_whitening_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl'  --model_path './target_models/hmdb51_slowfastnet_40.pt' --save_val_vec './pkl_data/hmdb_noise/hmdb51_slowfastnet_40_val_augmentation_zca_whitening_x_pre.pkl' --save_test_vec './pkl_data/hmdb_noise/hmdb51_slowfastnet_40_test_augmentation_zca_whitening_x_pre.pkl'


python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/hmdb_noise/augmentation_channel_shift_range_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl'  --model_path './target_models/hmdb51_R2Plus1D_90.pt' --save_val_vec './pkl_data/hmdb_noise/hmdb51_R2Plus1D_90_val_augmentation_channel_shift_range_x_pre.pkl' --save_test_vec './pkl_data/hmdb_noise/hmdb51_R2Plus1D_90_test_augmentation_channel_shift_range_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/hmdb_noise/augmentation_featurewise_std_normalization_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl'  --model_path './target_models/hmdb51_R2Plus1D_90.pt' --save_val_vec './pkl_data/hmdb_noise/hmdb51_R2Plus1D_90_val_augmentation_featurewise_std_normalization_x_pre.pkl' --save_test_vec './pkl_data/hmdb_noise/hmdb51_R2Plus1D_90_test_augmentation_featurewise_std_normalization_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/hmdb_noise/augmentation_height_shift_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl'  --model_path './target_models/hmdb51_R2Plus1D_90.pt' --save_val_vec './pkl_data/hmdb_noise/hmdb51_R2Plus1D_90_val_augmentation_height_shift_x_pre.pkl' --save_test_vec './pkl_data/hmdb_noise/hmdb51_R2Plus1D_90_test_augmentation_height_shift_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/hmdb_noise/augmentation_horizontal_flip_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl'  --model_path './target_models/hmdb51_R2Plus1D_90.pt' --save_val_vec './pkl_data/hmdb_noise/hmdb51_R2Plus1D_90_val_augmentation_horizontal_flip_x_pre.pkl' --save_test_vec './pkl_data/hmdb_noise/hmdb51_R2Plus1D_90_test_augmentation_horizontal_flip_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/hmdb_noise/augmentation_shear_range_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl'  --model_path './target_models/hmdb51_R2Plus1D_90.pt' --save_val_vec './pkl_data/hmdb_noise/hmdb51_R2Plus1D_90_val_augmentation_shear_range_x_pre.pkl' --save_test_vec './pkl_data/hmdb_noise/hmdb51_R2Plus1D_90_test_augmentation_shear_range_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/hmdb_noise/augmentation_width_shift_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl'  --model_path './target_models/hmdb51_R2Plus1D_90.pt' --save_val_vec './pkl_data/hmdb_noise/hmdb51_R2Plus1D_90_val_augmentation_width_shift_x_pre.pkl' --save_test_vec './pkl_data/hmdb_noise/hmdb51_R2Plus1D_90_test_augmentation_width_shift_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/hmdb_noise/augmentation_zca_whitening_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl'  --model_path './target_models/hmdb51_R2Plus1D_90.pt' --save_val_vec './pkl_data/hmdb_noise/hmdb51_R2Plus1D_90_val_augmentation_zca_whitening_x_pre.pkl' --save_test_vec './pkl_data/hmdb_noise/hmdb51_R2Plus1D_90_test_augmentation_zca_whitening_x_pre.pkl'


##############################################################################

python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/accident_noise/augmentation_channel_shift_range_x.pkl' --path_y './pkl_data/accident/accident_y.pkl'  --model_path './target_models/accident_C3D_10.pt' --save_val_vec './pkl_data/accident_noise/accident_C3D_10_val_augmentation_channel_shift_range_x_pre.pkl' --save_test_vec './pkl_data/accident_noise/accident_C3D_10_test_augmentation_channel_shift_range_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/accident_noise/augmentation_featurewise_std_normalization_x.pkl' --path_y './pkl_data/accident/accident_y.pkl'  --model_path './target_models/accident_C3D_10.pt' --save_val_vec './pkl_data/accident_noise/accident_C3D_10_val_augmentation_featurewise_std_normalization_x_pre.pkl' --save_test_vec './pkl_data/accident_noise/accident_C3D_10_test_augmentation_featurewise_std_normalization_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/accident_noise/augmentation_height_shift_x.pkl' --path_y './pkl_data/accident/accident_y.pkl'  --model_path './target_models/accident_C3D_10.pt' --save_val_vec './pkl_data/accident_noise/accident_C3D_10_val_augmentation_height_shift_x_pre.pkl' --save_test_vec './pkl_data/accident_noise/accident_C3D_10_test_augmentation_height_shift_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/accident_noise/augmentation_horizontal_flip_x.pkl' --path_y './pkl_data/accident/accident_y.pkl'  --model_path './target_models/accident_C3D_10.pt' --save_val_vec './pkl_data/accident_noise/accident_C3D_10_val_augmentation_horizontal_flip_x_pre.pkl' --save_test_vec './pkl_data/accident_noise/accident_C3D_10_test_augmentation_horizontal_flip_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/accident_noise/augmentation_shear_range_x.pkl' --path_y './pkl_data/accident/accident_y.pkl'  --model_path './target_models/accident_C3D_10.pt' --save_val_vec './pkl_data/accident_noise/accident_C3D_10_val_augmentation_shear_range_x_pre.pkl' --save_test_vec './pkl_data/accident_noise/accident_C3D_10_test_augmentation_shear_range_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/accident_noise/augmentation_width_shift_x.pkl' --path_y './pkl_data/accident/accident_y.pkl'  --model_path './target_models/accident_C3D_10.pt' --save_val_vec './pkl_data/accident_noise/accident_C3D_10_val_augmentation_width_shift_x_pre.pkl' --save_test_vec './pkl_data/accident_noise/accident_C3D_10_test_augmentation_width_shift_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/accident_noise/augmentation_zca_whitening_x.pkl' --path_y './pkl_data/accident/accident_y.pkl'  --model_path './target_models/accident_C3D_10.pt' --save_val_vec './pkl_data/accident_noise/accident_C3D_10_val_augmentation_zca_whitening_x_pre.pkl' --save_test_vec './pkl_data/accident_noise/accident_C3D_10_test_augmentation_zca_whitening_x_pre.pkl'

python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/accident_noise/augmentation_channel_shift_range_x.pkl' --path_y './pkl_data/accident/accident_y.pkl'  --model_path './target_models/accident_R3D_10.pt' --save_val_vec './pkl_data/accident_noise/accident_R3D_10_val_augmentation_channel_shift_range_x_pre.pkl' --save_test_vec './pkl_data/accident_noise/accident_R3D_10_test_augmentation_channel_shift_range_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/accident_noise/augmentation_featurewise_std_normalization_x.pkl' --path_y './pkl_data/accident/accident_y.pkl'  --model_path './target_models/accident_R3D_10.pt' --save_val_vec './pkl_data/accident_noise/accident_R3D_10_val_augmentation_featurewise_std_normalization_x_pre.pkl' --save_test_vec './pkl_data/accident_noise/accident_R3D_10_test_augmentation_featurewise_std_normalization_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/accident_noise/augmentation_height_shift_x.pkl' --path_y './pkl_data/accident/accident_y.pkl'  --model_path './target_models/accident_R3D_10.pt' --save_val_vec './pkl_data/accident_noise/accident_R3D_10_val_augmentation_height_shift_x_pre.pkl' --save_test_vec './pkl_data/accident_noise/accident_R3D_10_test_augmentation_height_shift_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/accident_noise/augmentation_horizontal_flip_x.pkl' --path_y './pkl_data/accident/accident_y.pkl'  --model_path './target_models/accident_R3D_10.pt' --save_val_vec './pkl_data/accident_noise/accident_R3D_10_val_augmentation_horizontal_flip_x_pre.pkl' --save_test_vec './pkl_data/accident_noise/accident_R3D_10_test_augmentation_horizontal_flip_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/accident_noise/augmentation_shear_range_x.pkl' --path_y './pkl_data/accident/accident_y.pkl'  --model_path './target_models/accident_R3D_10.pt' --save_val_vec './pkl_data/accident_noise/accident_R3D_10_val_augmentation_shear_range_x_pre.pkl' --save_test_vec './pkl_data/accident_noise/accident_R3D_10_test_augmentation_shear_range_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/accident_noise/augmentation_width_shift_x.pkl' --path_y './pkl_data/accident/accident_y.pkl'  --model_path './target_models/accident_R3D_10.pt' --save_val_vec './pkl_data/accident_noise/accident_R3D_10_val_augmentation_width_shift_x_pre.pkl' --save_test_vec './pkl_data/accident_noise/accident_R3D_10_test_augmentation_width_shift_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/accident_noise/augmentation_zca_whitening_x.pkl' --path_y './pkl_data/accident/accident_y.pkl'  --model_path './target_models/accident_R3D_10.pt' --save_val_vec './pkl_data/accident_noise/accident_R3D_10_val_augmentation_zca_whitening_x_pre.pkl' --save_test_vec './pkl_data/accident_noise/accident_R3D_10_test_augmentation_zca_whitening_x_pre.pkl'

python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/accident_noise/augmentation_channel_shift_range_x.pkl' --path_y './pkl_data/accident/accident_y.pkl'  --model_path './target_models/accident_R2Plus1D_50.pt' --save_val_vec './pkl_data/accident_noise/accident_R2Plus1D_50_val_augmentation_channel_shift_range_x_pre.pkl' --save_test_vec './pkl_data/accident_noise/accident_R2Plus1D_50_test_augmentation_channel_shift_range_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/accident_noise/augmentation_featurewise_std_normalization_x.pkl' --path_y './pkl_data/accident/accident_y.pkl'  --model_path './target_models/accident_R2Plus1D_50.pt' --save_val_vec './pkl_data/accident_noise/accident_R2Plus1D_50_val_augmentation_featurewise_std_normalization_x_pre.pkl' --save_test_vec './pkl_data/accident_noise/accident_R2Plus1D_50_test_augmentation_featurewise_std_normalization_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/accident_noise/augmentation_height_shift_x.pkl' --path_y './pkl_data/accident/accident_y.pkl'  --model_path './target_models/accident_R2Plus1D_50.pt' --save_val_vec './pkl_data/accident_noise/accident_R2Plus1D_50_val_augmentation_height_shift_x_pre.pkl' --save_test_vec './pkl_data/accident_noise/accident_R2Plus1D_50_test_augmentation_height_shift_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/accident_noise/augmentation_horizontal_flip_x.pkl' --path_y './pkl_data/accident/accident_y.pkl'  --model_path './target_models/accident_R2Plus1D_50.pt' --save_val_vec './pkl_data/accident_noise/accident_R2Plus1D_50_val_augmentation_horizontal_flip_x_pre.pkl' --save_test_vec './pkl_data/accident_noise/accident_R2Plus1D_50_test_augmentation_horizontal_flip_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/accident_noise/augmentation_shear_range_x.pkl' --path_y './pkl_data/accident/accident_y.pkl'  --model_path './target_models/accident_R2Plus1D_50.pt' --save_val_vec './pkl_data/accident_noise/accident_R2Plus1D_50_val_augmentation_shear_range_x_pre.pkl' --save_test_vec './pkl_data/accident_noise/accident_R2Plus1D_50_test_augmentation_shear_range_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/accident_noise/augmentation_width_shift_x.pkl' --path_y './pkl_data/accident/accident_y.pkl'  --model_path './target_models/accident_R2Plus1D_50.pt' --save_val_vec './pkl_data/accident_noise/accident_R2Plus1D_50_val_augmentation_width_shift_x_pre.pkl' --save_test_vec './pkl_data/accident_noise/accident_R2Plus1D_50_test_augmentation_width_shift_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/accident_noise/augmentation_zca_whitening_x.pkl' --path_y './pkl_data/accident/accident_y.pkl'  --model_path './target_models/accident_R2Plus1D_50.pt' --save_val_vec './pkl_data/accident_noise/accident_R2Plus1D_50_val_augmentation_zca_whitening_x_pre.pkl' --save_test_vec './pkl_data/accident_noise/accident_R2Plus1D_50_test_augmentation_zca_whitening_x_pre.pkl'

python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/accident_noise/augmentation_channel_shift_range_x.pkl' --path_y './pkl_data/accident/accident_y.pkl'  --model_path './target_models/accident_slowfastnet_40.pt' --save_val_vec './pkl_data/accident_noise/accident_slowfastnet_40_val_augmentation_channel_shift_range_x_pre.pkl' --save_test_vec './pkl_data/accident_noise/accident_slowfastnet_40_test_augmentation_channel_shift_range_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/accident_noise/augmentation_featurewise_std_normalization_x.pkl' --path_y './pkl_data/accident/accident_y.pkl'  --model_path './target_models/accident_slowfastnet_40.pt' --save_val_vec './pkl_data/accident_noise/accident_slowfastnet_40_val_augmentation_featurewise_std_normalization_x_pre.pkl' --save_test_vec './pkl_data/accident_noise/accident_slowfastnet_40_test_augmentation_featurewise_std_normalization_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/accident_noise/augmentation_height_shift_x.pkl' --path_y './pkl_data/accident/accident_y.pkl'  --model_path './target_models/accident_slowfastnet_40.pt' --save_val_vec './pkl_data/accident_noise/accident_slowfastnet_40_val_augmentation_height_shift_x_pre.pkl' --save_test_vec './pkl_data/accident_noise/accident_slowfastnet_40_test_augmentation_height_shift_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/accident_noise/augmentation_horizontal_flip_x.pkl' --path_y './pkl_data/accident/accident_y.pkl'  --model_path './target_models/accident_slowfastnet_40.pt' --save_val_vec './pkl_data/accident_noise/accident_slowfastnet_40_val_augmentation_horizontal_flip_x_pre.pkl' --save_test_vec './pkl_data/accident_noise/accident_slowfastnet_40_test_augmentation_horizontal_flip_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/accident_noise/augmentation_shear_range_x.pkl' --path_y './pkl_data/accident/accident_y.pkl'  --model_path './target_models/accident_slowfastnet_40.pt' --save_val_vec './pkl_data/accident_noise/accident_slowfastnet_40_val_augmentation_shear_range_x_pre.pkl' --save_test_vec './pkl_data/accident_noise/accident_slowfastnet_40_test_augmentation_shear_range_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/accident_noise/augmentation_width_shift_x.pkl' --path_y './pkl_data/accident/accident_y.pkl'  --model_path './target_models/accident_slowfastnet_40.pt' --save_val_vec './pkl_data/accident_noise/accident_slowfastnet_40_val_augmentation_width_shift_x_pre.pkl' --save_test_vec './pkl_data/accident_noise/accident_slowfastnet_40_test_augmentation_width_shift_x_pre.pkl'
python get_video_model_pre.py --cuda 'cuda:0' --path_x './pkl_data/accident_noise/augmentation_zca_whitening_x.pkl' --path_y './pkl_data/accident/accident_y.pkl'  --model_path './target_models/accident_slowfastnet_40.pt' --save_val_vec './pkl_data/accident_noise/accident_slowfastnet_40_val_augmentation_zca_whitening_x_pre.pkl' --save_test_vec './pkl_data/accident_noise/accident_slowfastnet_40_test_augmentation_zca_whitening_x_pre.pkl'


