#!/bin/bash -l
#SBATCH -N 1
#SBATCH --mail-type=end,fail
#SBATCH --mail-user=yinghua.li@uni.lu
#SBATCH -n 2
#SBATCH -p gpu
#SBATCH --gres=gpu:2
#SBATCH --time=1-12:00:00

source activate py37

python vrank_apfd_vt.py --path_model_save './target_models/accident_vt.h5' --path_frame './pkl_data/accident/accident_x.pkl' --path_x './pkl_data/accident/vt_accident_x.pkl' --path_y './pkl_data/accident/accident_y.pkl' --path_x_embedding './pkl_data/accident/accident_x_embedding.pkl' --save_path './results/vt_accident_x.json' --num_classes 12
python vrank_apfd_vt.py --path_model_save './target_models/hmdb51_vt.h5' --path_frame './pkl_data/hmdb51/hmdb51_x.pkl' --path_x './pkl_data/hmdb51/vt_hmdb51_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl' --path_x_embedding './pkl_data/hmdb51/hmdb51_x_embedding.pkl' --save_path './results/vt_hmdb51_x.json' --num_classes 51
python vrank_apfd_vt.py --path_model_save './target_models/ucf101_vt.h5' --path_frame './pkl_data/ucf101/ucf101_x.pkl' --path_x './pkl_data/ucf101/vt_ucf101_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_x_embedding './pkl_data/ucf101/ucf101_x_embedding.pkl' --save_path './results/vt_ucf101_x.json' --num_classes 101


python vrank_apfd_vt.py --path_model_save './target_models/accident_vt.h5' --path_frame './pkl_data/accident_noise/augmentation_channel_shift_range_x.pkl' --path_x './pkl_data/accident_noise/vt_augmentation_channel_shift_range_x.pkl' --path_y './pkl_data/accident/accident_y.pkl' --path_x_embedding './pkl_data/accident_noise/augmentation_channel_shift_range_x_embedding.pkl' --save_path './results/vt_accident_augmentation_channel_shift_range_x.json' --num_classes 12
python vrank_apfd_vt.py --path_model_save './target_models/accident_vt.h5' --path_frame './pkl_data/accident_noise/augmentation_featurewise_std_normalization.pkl' --path_x './pkl_data/accident_noise/vt_augmentation_featurewise_std_normalization.pkl' --path_y './pkl_data/accident/accident_y.pkl' --path_x_embedding './pkl_data/accident_noise/augmentation_featurewise_std_normalization_embedding.pkl' --save_path './results/vt_accident_augmentation_featurewise_std_normalization.json' --num_classes 12
python vrank_apfd_vt.py --path_model_save './target_models/accident_vt.h5' --path_frame './pkl_data/accident_noise/augmentation_height_shift_x.pkl' --path_x './pkl_data/accident_noise/vt_augmentation_height_shift_x.pkl' --path_y './pkl_data/accident/accident_y.pkl' --path_x_embedding './pkl_data/accident_noise/augmentation_height_shift_x_embedding.pkl' --save_path './results/vt_accident_augmentation_height_shift_x.json' --num_classes 12
python vrank_apfd_vt.py --path_model_save './target_models/accident_vt.h5' --path_frame './pkl_data/accident_noise/augmentation_horizontal_flip_x.pkl' --path_x './pkl_data/accident_noise/vt_augmentation_horizontal_flip_x.pkl' --path_y './pkl_data/accident/accident_y.pkl' --path_x_embedding './pkl_data/accident_noise/augmentation_horizontal_flip_x_embedding.pkl' --save_path './results/vt_accident_augmentation_horizontal_flip_x.json' --num_classes 12
python vrank_apfd_vt.py --path_model_save './target_models/accident_vt.h5' --path_frame './pkl_data/accident_noise/augmentation_shear_range_x.pkl' --path_x './pkl_data/accident_noise/vt_augmentation_shear_range_x.pkl' --path_y './pkl_data/accident/accident_y.pkl' --path_x_embedding './pkl_data/accident_noise/augmentation_shear_range_x_embedding.pkl' --save_path './results/vt_accident_augmentation_shear_range_x.json' --num_classes 12
python vrank_apfd_vt.py --path_model_save './target_models/accident_vt.h5' --path_frame './pkl_data/accident_noise/augmentation_width_shift_x.pkl' --path_x './pkl_data/accident_noise/vt_augmentation_width_shift_x.pkl' --path_y './pkl_data/accident/accident_y.pkl' --path_x_embedding './pkl_data/accident_noise/augmentation_width_shift_x_embedding.pkl' --save_path './results/vt_accident_augmentation_width_shift_x.json' --num_classes 12
python vrank_apfd_vt.py --path_model_save './target_models/accident_vt.h5' --path_frame './pkl_data/accident_noise/augmentation_zca_whitening_x.pkl' --path_x './pkl_data/accident_noise/vt_augmentation_zca_whitening_x.pkl' --path_y './pkl_data/accident/accident_y.pkl' --path_x_embedding './pkl_data/accident_noise/augmentation_zca_whitening_x_embedding.pkl' --save_path './results/vt_accident_augmentation_zca_whitening_x.json' --num_classes 12

python vrank_apfd_vt.py --path_model_save './target_models/hmdb51_vt.h5' --path_frame './pkl_data/hmdb51_noise/augmentation_channel_shift_range_x.pkl' --path_x './pkl_data/hmdb51_noise/vt_augmentation_channel_shift_range_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl' --path_x_embedding './pkl_data/hmdb51_noise/augmentation_channel_shift_range_x_embedding.pkl' --save_path './results/vt_hmdb51_augmentation_channel_shift_range_x.json' --num_classes 51
python vrank_apfd_vt.py --path_model_save './target_models/hmdb51_vt.h5' --path_frame './pkl_data/hmdb51_noise/augmentation_featurewise_std_normalization.pkl' --path_x './pkl_data/hmdb51_noise/vt_augmentation_featurewise_std_normalization.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl' --path_x_embedding './pkl_data/hmdb51_noise/augmentation_featurewise_std_normalization_embedding.pkl' --save_path './results/vt_hmdb51_augmentation_featurewise_std_normalization.json' --num_classes 51
python vrank_apfd_vt.py --path_model_save './target_models/hmdb51_vt.h5' --path_frame './pkl_data/hmdb51_noise/augmentation_height_shift_x.pkl' --path_x './pkl_data/hmdb51_noise/vt_augmentation_height_shift_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl' --path_x_embedding './pkl_data/hmdb51_noise/augmentation_height_shift_x_embedding.pkl' --save_path './results/vt_hmdb51_augmentation_height_shift_x.json' --num_classes 51
python vrank_apfd_vt.py --path_model_save './target_models/hmdb51_vt.h5' --path_frame './pkl_data/hmdb51_noise/augmentation_horizontal_flip_x.pkl' --path_x './pkl_data/hmdb51_noise/vt_augmentation_horizontal_flip_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl' --path_x_embedding './pkl_data/hmdb51_noise/augmentation_horizontal_flip_x_embedding.pkl' --save_path './results/vt_hmdb51_augmentation_horizontal_flip_x.json' --num_classes 51
python vrank_apfd_vt.py --path_model_save './target_models/hmdb51_vt.h5' --path_frame './pkl_data/hmdb51_noise/augmentation_shear_range_x.pkl' --path_x './pkl_data/hmdb51_noise/vt_augmentation_shear_range_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl' --path_x_embedding './pkl_data/hmdb51_noise/augmentation_shear_range_x_embedding.pkl' --save_path './results/vt_hmdb51_augmentation_shear_range_x.json' --num_classes 51
python vrank_apfd_vt.py --path_model_save './target_models/hmdb51_vt.h5' --path_frame './pkl_data/hmdb51_noise/augmentation_width_shift_x.pkl' --path_x './pkl_data/hmdb51_noise/vt_augmentation_width_shift_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl' --path_x_embedding './pkl_data/hmdb51_noise/augmentation_width_shift_x_embedding.pkl' --save_path './results/vt_hmdb51_augmentation_width_shift_x.json' --num_classes 51
python vrank_apfd_vt.py --path_model_save './target_models/hmdb51_vt.h5' --path_frame './pkl_data/hmdb51_noise/augmentation_zca_whitening_x.pkl' --path_x './pkl_data/hmdb51_noise/vt_augmentation_zca_whitening_x.pkl' --path_y './pkl_data/hmdb51/hmdb51_y.pkl' --path_x_embedding './pkl_data/hmdb51_noise/augmentation_zca_whitening_x_embedding.pkl' --save_path './results/vt_hmdb51_augmentation_zca_whitening_x.json' --num_classes 51

python vrank_apfd_vt.py --path_model_save './target_models/ucf101_vt.h5' --path_frame './pkl_data/ucf101_noise/augmentation_channel_shift_range_x.pkl' --path_x './pkl_data/ucf101_noise/vt_augmentation_channel_shift_range_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_x_embedding './pkl_data/ucf101_noise/augmentation_channel_shift_range_x_embedding.pkl' --save_path './results/vt_ucf101_augmentation_channel_shift_range_x.json' --num_classes 101
python vrank_apfd_vt.py --path_model_save './target_models/ucf101_vt.h5' --path_frame './pkl_data/ucf101_noise/augmentation_featurewise_std_normalization.pkl' --path_x './pkl_data/ucf101_noise/vt_augmentation_featurewise_std_normalization.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_x_embedding './pkl_data/ucf101_noise/augmentation_featurewise_std_normalization_embedding.pkl' --save_path './results/vt_ucf101_augmentation_featurewise_std_normalization.json' --num_classes 101
python vrank_apfd_vt.py --path_model_save './target_models/ucf101_vt.h5' --path_frame './pkl_data/ucf101_noise/augmentation_height_shift_x.pkl' --path_x './pkl_data/ucf101_noise/vt_augmentation_height_shift_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_x_embedding './pkl_data/ucf101_noise/augmentation_height_shift_x_embedding.pkl' --save_path './results/vt_ucf101_augmentation_height_shift_x.json' --num_classes 101
python vrank_apfd_vt.py --path_model_save './target_models/ucf101_vt.h5' --path_frame './pkl_data/ucf101_noise/augmentation_horizontal_flip_x.pkl' --path_x './pkl_data/ucf101_noise/vt_augmentation_horizontal_flip_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_x_embedding './pkl_data/ucf101_noise/augmentation_horizontal_flip_x_embedding.pkl' --save_path './results/vt_ucf101_augmentation_horizontal_flip_x.json' --num_classes 101
python vrank_apfd_vt.py --path_model_save './target_models/ucf101_vt.h5' --path_frame './pkl_data/ucf101_noise/augmentation_shear_range_x.pkl' --path_x './pkl_data/ucf101_noise/vt_augmentation_shear_range_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_x_embedding './pkl_data/ucf101_noise/augmentation_shear_range_x_embedding.pkl' --save_path './results/vt_ucf101_augmentation_shear_range_x.json' --num_classes 101
python vrank_apfd_vt.py --path_model_save './target_models/ucf101_vt.h5' --path_frame './pkl_data/ucf101_noise/augmentation_width_shift_x.pkl' --path_x './pkl_data/ucf101_noise/vt_augmentation_width_shift_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_x_embedding './pkl_data/ucf101_noise/augmentation_width_shift_x_embedding.pkl' --save_path './results/vt_ucf101_augmentation_width_shift_x.json' --num_classes 101
python vrank_apfd_vt.py --path_model_save './target_models/ucf101_vt.h5' --path_frame './pkl_data/ucf101_noise/augmentation_zca_whitening_x.pkl' --path_x './pkl_data/ucf101_noise/vt_augmentation_zca_whitening_x.pkl' --path_y './pkl_data/ucf101/ucf101_y.pkl' --path_x_embedding './pkl_data/ucf101_noise/augmentation_zca_whitening_x_embedding.pkl' --save_path './results/vt_ucf101_augmentation_zca_whitening_x.json' --num_classes 101

